---
abstract: 'fork test'
author:
  - 'Tokuhiro Matsuno <tokuhirom  slkjfd gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-SharedFork
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  IPC::ShareLite: 0.17
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
